services:
  java_maven:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: Java_Maven
    volumes:
      - .:/etc/app:delegated
    working_dir: /etc/app
    command: tail -f /dev/null
